using MongoDB.Bson;
using MongoDB.Driver;
using MyTelegram.Messenger.Services.Bots;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Messages;
/// <summary>
/// Obtain a <a href="https://corefork.telegram.org/api/bots/inline#21-using-a-prepared-inline-message">prepared inline message</a> generated by a <a href="https://corefork.telegram.org/api/bots/webapps">mini app</a>: invoked when handling <a href="https://corefork.telegram.org/api/web-events#web-app-send-prepared-message">web_app_send_prepared_message events</a>
/// Possible errors
/// Code Type Description
/// 400 ID_EXPIRED The passed prepared inline message ID has expired.
/// 400 ID_INVALID The passed ID is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/messages.getPreparedInlineMessage"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class GetPreparedInlineMessageHandler(
    IMongoDatabase mongoDatabase,
    IUserAppService userAppService,
    IAccessHashHelper accessHashHelper,
    IUserConverterService userConverterService) : RpcResultObjectHandler<MyTelegram.Schema.Messages.RequestGetPreparedInlineMessage, MyTelegram.Schema.Messages.IPreparedInlineMessage>
{
    private const string Collection = "prepared_inline_messages";
    private const string ResultsCollection = "inline_bot_results";

    /// <summary>How long the materialised query id stays usable by sendInlineBotResult.</summary>
    private static readonly TimeSpan ResultsRetention = TimeSpan.FromHours(1);

    protected override async Task<MyTelegram.Schema.Messages.IPreparedInlineMessage> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Messages.RequestGetPreparedInlineMessage obj)
    {
        if (obj.Bot is not TInputUser inputBot)
        {
            RpcErrors.RpcErrors400.IdInvalid.ThrowRpcError();
            return null!;
        }

        await accessHashHelper.CheckAccessHashAsync(input, inputBot.UserId, inputBot.AccessHash);

        if (string.IsNullOrEmpty(obj.Id))
        {
            RpcErrors.RpcErrors400.IdInvalid.ThrowRpcError();
        }

        var filter = Builders<BsonDocument>.Filter.And(
            Builders<BsonDocument>.Filter.Eq("id", obj.Id),
            Builders<BsonDocument>.Filter.Eq("bot_id", inputBot.UserId),
            Builders<BsonDocument>.Filter.Eq("user_id", input.UserId));

        var doc = await mongoDatabase.GetCollection<BsonDocument>(Collection).Find(filter).FirstOrDefaultAsync();
        if (doc == null)
        {
            RpcErrors.RpcErrors400.IdInvalid.ThrowRpcError();
        }

        var expireDate = GetInt32(doc!, "expire_date");
        if (expireDate > 0 && expireDate < DateTime.UtcNow.ToTimestamp())
        {
            await mongoDatabase.GetCollection<BsonDocument>(Collection).DeleteOneAsync(filter);
            RpcErrors.RpcErrors400.IdExpired.ThrowRpcError();
        }

        var inputResult = ReadObject<IInputBotInlineResult>(doc!, "result");
        if (inputResult == null)
        {
            RpcErrors.RpcErrors400.IdInvalid.ThrowRpcError();
        }

        var result = InlineResultConverter.ToBotInlineResult(inputResult!);
        if (result == null)
        {
            RpcErrors.RpcErrors400.IdInvalid.ThrowRpcError();
        }

        var peerTypes = ReadObject<TVector<IInlineQueryPeerType>>(doc!, "peer_types") ??
                        new TVector<IInlineQueryPeerType>();

        // sendInlineBotResult works off inline_bot_results, so materialise an entry for this
        // prepared message; otherwise the query id we hand back could not be used to send it.
        var queryId = Random.Shared.NextInt64();
        await mongoDatabase.GetCollection<BsonDocument>(ResultsCollection).InsertOneAsync(new BsonDocument
        {
            ["_id"] = $"inline-results-{queryId}",
            ["query_id"] = queryId,
            ["bot_id"] = inputBot.UserId,
            ["user_id"] = input.UserId,
            ["query"] = string.Empty,
            ["gallery"] = false,
            ["private"] = false,
            ["cache_time"] = 0,
            ["next_offset"] = string.Empty,
            ["switch_pm"] = Array.Empty<byte>(),
            ["switch_webview"] = Array.Empty<byte>(),
            ["results"] = new TVector<IBotInlineResult>(result!).ToBytes(),
            ["input_results"] = new TVector<IInputBotInlineResult>(inputResult!).ToBytes(),
            ["expires_at"] = DateTime.UtcNow.Add(ResultsRetention).ToTimestamp()
        });

        var users = new TVector<IUser>();
        var botUser = await userAppService.GetAsync(inputBot.UserId);
        if (botUser != null)
        {
            users.Add(userConverterService.ToUser(input, botUser, layer: input.Layer));
        }

        return new MyTelegram.Schema.Messages.TPreparedInlineMessage
        {
            QueryId = queryId,
            Result = result!,
            PeerTypes = peerTypes,
            CacheTime = 0,
            Users = users
        };
    }

    private static T? ReadObject<T>(BsonDocument doc, string name) where T : class, IObject
    {
        if (!doc.TryGetValue(name, out var value) || value.BsonType != BsonType.Binary)
        {
            return null;
        }

        var bytes = value.AsBsonBinaryData.Bytes;
        if (bytes.Length == 0)
        {
            return null;
        }

        var buffer = new ReadOnlyMemory<byte>(bytes);
        return buffer.Read<T>();
    }

    private static int GetInt32(BsonDocument doc, string name)
    {
        if (!doc.TryGetValue(name, out var value))
        {
            return 0;
        }

        return value.BsonType switch
        {
            BsonType.Int32 => value.AsInt32,
            BsonType.Int64 => (int)value.AsInt64,
            BsonType.Double => (int)value.AsDouble,
            _ => 0
        };
    }
}
